### ISSUE TITLE
Things to fix that I saw

### ISSUE THREAD

**Issue by jlengrand** [SimpleWebConf/SimpleWebConf.github.io#2]
Hoi, 

Just listing here instead of spamming the chat :). Making it as a TODO list

- [x] powered by not centered : 
![image](https://user-images.githubusercontent.com/921666/113512468-16b30a80-9565-11eb-87bf-b740e62dd993.png)
- [x] Icon very big next to conference title
![image](https://user-images.githubusercontent.com/921666/113512505-3c401400-9565-11eb-9461-91e133e9d5cf.png)
It's not as disturbing when landing, maybe it's because of the black color.
- [x] Logo ( and title bar) shows up on CoC page
![image](https://user-images.githubusercontent.com/921666/113512537-61348700-9565-11eb-9b7d-79df80798fa4.png)
- [ ] I would vote to remove animations. We don't have them consistently (for example only half the committee has them), and they use up js for nothing. 
- [ ] About in title -> Team ? 
- [ ] Mobile seems sometimes very broken ( lots of white space, happens with half of the mobiles I tried)
![image](https://user-images.githubusercontent.com/921666/113512641-d1dba380-9565-11eb-9c0f-09a806357507.png)
- [x] This is ipad pro, logo is completely misplaced : 
![image](https://user-images.githubusercontent.com/921666/113512654-e455dd00-9565-11eb-9d36-ddac78559949.png)
- [ ] Mobile menu bar overflows : 
![image](https://user-images.githubusercontent.com/921666/113512674-ff285180-9565-11eb-85d4-9ffd242adaa4.png)
- [x] Mobile buttons are too big : 
![image](https://user-images.githubusercontent.com/921666/113512686-0fd8c780-9566-11eb-85d7-f3e4124d3531.png)
- [ ] Mobile I see white lines on the separators : 
![image](https://user-images.githubusercontent.com/921666/113512704-22530100-9566-11eb-9028-495e2ea4fd58.png)

**Comment by korzio** [comment]
https://github.com/SimpleWebConf/SimpleWebConf.github.io/pull/3
